version: '3'
services:
  graphdb:
    image: ontotext/graphdb:10.0.2
    ports:
      # HTTP
      - 7200:7200
    volumes:
      - ./plugins:/opt/graphdb/home/plugins
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.extra.plugins=/opt/graphdb/home/plugins
